fixest::setFixest_dict(
    brownness_share_2013 = "Brown share",
    share_manufacturing_2013 = "Share of manufacturing 2013",
    pop_density_2013 = "Population density 2013",
    scaled_share_manufacturing_2013 = "Share of manufacturing 2013",
    scaled_pop_density_2013 = "Population density 2013",
    hh_income_vgrdl = "Household income",
    gdp_pc_ardeco = "GDP per capita",
    share_manufacturing_regstat = "Share manufacturing",
    pop_density = "Population density",
    population = "Population",
    schulabganger_mit_allgemeiner_hochschulreife_inkar = "Share high school graduates",
    arbeitslosenquote_inkar = "Unemployment rate",
    brown0_3_share_2013 = "Brown share",
    auslanderanteil_inkar = "Share foreigners",
    scaled_hh_income_vgrdl = "Household income",
    scaled_gdp_pc_ardeco = "GDP per capita",
    scaled_arbeitslosenquote_inkar = "Unemployment rate",
    scaled_schulabganger_mit_allgemeiner_hochschulreife_inkar = "Share high school graduates",
    scaled_auslanderanteil_inkar = "Share foreigners",
    scaled_pop_density = "Population density",
    scaled_population = "Population",
    election_year = "Election",
    scaled_share_manufacturing_regstat = "Share manufacturing"
)
